### ISSUE TITLE
Bug in reading QCS credentials

### ISSUE THREAD

**Issue by kalzoo** [rigetti/qcs-sdk-rust#27]
On QCS JupyterHub, you can see this error when running any program compiled with the QCS SDK:

```
error in execution: When refreshing authentication token

Caused by:
    No refresh token is in secrets
```

This is despite a properly-formatted and present `~/.qcs/secrets.toml`:

```toml

[credentials]

  [credentials.default]

    [credentials.default.token_payload]
      access_token = "valid"
      id_token = ""
      refresh_token = "valid"
      scope = "valid"
      token_type = "Bearer"
```

This does not occur on the two developer machines tried, outside of jupyterhub; occurred for two different JH users. It will work for local credentials, but not in JH when those same local credentials are pasted/uploaded into JH.
